const env = process.env;

module.exports = {
    MONGO_CONNECT_STRING: env.MONGO_CONNECT_STRING || 'mongodb://0.0.0.0/admin',
    MONGO_RETRY_COUNT: env.MONGO_RETRY_COUNT || 20,
    MONGO_RETRY_WAIT: env.MONGO_RETRY_WAIT || 3000,
    BLOCKCHAIN_RETRY_COUNT: env.BLOCKCHAIN_RETRY_COUNT || 20,
    BLOCKCHAIN_RETRY_WAIT: env.BLOCKCHAIN_RETRY_COUNT || 3000,
    DAY_START: env.DAY_START || 3,
};
